import json
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import User, Recommendation
from ..schemas import RecommendationSummary, RecommendationDetailResponse
from ..auth import get_current_user

router = APIRouter(tags=["History & Recommendations"])

@router.get("/history", response_model=List[RecommendationSummary])
def get_user_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieves all past recommendations generated by the authenticated user."""
    records = db.query(Recommendation).filter(
        Recommendation.user_id == current_user.id
    ).order_by(Recommendation.created_at.desc()).all()
    return records


@router.get("/recommendations-details", response_model=RecommendationDetailResponse)
def get_recommendation_details_query(
    id: int = Query(..., description="The ID of the recommendation to retrieve"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    Retrieves detailed recommendation payload matching the specified ID query parameter.
    Route explicitly required by project brief: /recommendations-details
    """
    rec = db.query(Recommendation).filter(
        Recommendation.id == id,
        Recommendation.user_id == current_user.id
    ).first()

    if not rec:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Recommendation with ID {id} not found or not owned by user."
        )

    parsed_details = json.loads(rec.details) if isinstance(rec.details, str) else rec.details
    return RecommendationDetailResponse(
        id=rec.id,
        user_id=rec.user_id,
        category=rec.category,
        title=rec.title,
        budget=rec.budget,
        total_estimated_cost=rec.total_estimated_cost,
        remaining_budget=rec.remaining_budget,
        is_sample_data=rec.is_sample_data,
        details=parsed_details,
        created_at=rec.created_at
    )


@router.get("/recommendations-details/{id}", response_model=RecommendationDetailResponse)
def get_recommendation_details_path(
    id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieves detailed recommendation payload using path parameter."""
    return get_recommendation_details_query(id=id, current_user=current_user, db=db)


@router.delete("/history/{id}")
def delete_history_item(
    id: int,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Deletes a recommendation record from history."""
    rec = db.query(Recommendation).filter(
        Recommendation.id == id,
        Recommendation.user_id == current_user.id
    ).first()

    if not rec:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Recommendation with ID {id} not found."
        )

    db.delete(rec)
    db.commit()
    return {"status": "success", "message": f"Recommendation {id} removed."}

